<?php
/**
 * Copyright (c) 2012 Marco Graetsch
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without restriction,
 * including without limitation the rights to use, copy, modify, merge,
 * publish, distribute, sublicense, and/or sell copies of the Software,
 * and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
 * CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
 * TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
 * SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 *
 *
 * @package		Magdev_Tinycon
 * @author		Marco Graetsch <info@magdev.de>
 * @copyright	2012 Marco Graetsch
 */

$_fallback = $this->getFallback();
if ($_fallback) {
    if ($_fallback != '"force"') {
        $_fallback = 'true';
    }
} else {
    $_fallback = 'false';
}
?>
<?php if ($this->isEnabled()) { ?>
    <script type="text/javascript">
    $(document).observe('dom:loaded', function() {
        Tinycon.setOptions({
            width: <?php echo $this->getWidth() ?>,
            height: <?php echo $this->getHeight() ?>,
            font: '<?php echo $this->getFont() ?>',
            colour: '<?php echo $this->getColor() ?>',
            background: '<?php echo $this->getBackground() ?>',
            fallback: <?php echo $_fallback ?>,
            abbreviate: <?php echo $this->getAbbreviate() ? 'true' : 'false' ?>
        });
        Tinycon.setBubble(<?php echo $this->getCount() ?>);
    });
    </script>
<?php } ?>